---
- name: Clusters_Info playbook
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Read configuration
    set_fact:
        config: "{{ lookup('file', 'templates/config.json') }}"

  - name: add data services IP
    uri:
        url: "{{ nutanix_url }}/dataservices"
        user: "{{ vault_pe_username }}"
        password: "{{ vault_pe_password }}"
        method: PUT
        body: "{{ config.dataservice }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        status_code: 200, 201
        headers:
                Content-Type: application/json
        return_content: yes
    register: add_data_services_ip

