---
- name: Clusters_Info playbook
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Read configuration
    set_fact:
        config: "{{ lookup('file', 'templates/config.json') }}"

  - name: get storage pools
    uri:
      url: "{{ nutanix_urlv1 }}/storage_pools"
      user: "{{ vault_pe_username }}"
      password: "{{ vault_pe_password }}"
      method: GET
      force_basic_auth: yes
      validate_certs: no
      body_format: json
      headers:
        Content-Type: application/json
      return_content: yes
    register: cluster_storage_pools

  - name: Store Storage pool UUID
    set_fact:
            default_storage_pool_uuid: "{{ cluster_storage_pools.json.entities[0].storagePoolUuid }}"
        
  - name: Print storage pool
    debug:
            msg: "{{ default_storage_pool_uuid }}"

  - name: create Storage Pool
    uri:
        url: "{{ nutanix_urlv1 }}/storage_containers"
        user: "{{ vault_pe_username }}"
        password: "{{ vault_pe_password }}"
        method: POST
        body: "{{ config.storagecontainer }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        status_code: 200, 201
        headers:
                Content-Type: application/json
        return_content: yes
    register: storage_container

